name: My Node Workflow

on: [push]

jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo "test run"
    
    build-node:
        runs-on: ubuntu-latest
        needs: say-hello
        strategy:
            matrix:
                node-version: [18.x, 20.x]
        
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                    node-version: ${{ matrix.node-version }}
                    cache: 'npm'
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test
